name: Automate Deployment for Flutter

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Running the upgrades
        run: flutter upgrade

      - name: Build Flutter App
        run: flutter build web --web-renderer html --release

      - name: Deploy to cPanel via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          port: 17177  # Specify your cPanel SSH port
          script: |
            export TERM=xterm
            cd /home/techozon/deployflutterapp.techozon.com
            # Remove previous build
            rm -rf build

            # Pull the latest changes
            git reset --hard
            git pull origin dev

            # Install dependencies (if needed)
            flutter pub get

      - name: Notify on Success 544
        if: success()
        run: echo "Deployment successful!"

      - name: Notify on Failure 2 
        if: failure()
        run: echo "Deployment failed!"

