name: Automate Deployment for Flutter

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Running the upgrades
        run: flutter upgrade

      - name: Build Flutter App
        run: flutter build web --web-renderer html --release

      - name: Deploy to cPanel
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          port: 17177  # Specify your cPanel SSH port
          script: |
            export TERM=xterm
            git config --global --add safe.directory /home/cmjbuggy/crmdev.atvandbuggy.com
            cd /home/cmjbuggy/crmdev.atvandbuggy.com
            # Remove previous build
            rm -rf build

            # Pull the latest changes
            git reset --hard
            git pull origin dev

            # Install dependencies (if needed)
            flutter pub get

            # Additional commands to troubleshoot the tput error
            export TERM=xterm
            git config --global --add safe.directory /home/cmjbuggy/crmdev.atvandbuggy.com
            cd /home/cmjbuggy/crmdev.atvandbuggy.com
            

      - name: Notify on success
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: success
          fields: repo,commit
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_USERNAME: 'Build Info'

      - name: Notify on failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          fields: repo,commit
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_USERNAME: 'Build Info'
